### ISSUE TITLE
Less verbose grunt logging by default

### ISSUE THREAD

**Issue by RyanSylvestre** [clavery/grunt-copy-to#2]
Would it be possible to add a less verbose options for the grunt logging? Either by configuration or do what grunt-contrib-copy uses and make the default a summary with the option of verbosity.

From grunt-contrib-copy

> 2013-03-26   v0.4.1   Output summary by default ("Copied N files, created M folders"). Individual transaction output available via --verbose.

**Comment by clavery** [comment]
This is a good idea. I changed the default to display a colored summary line. The old output should be available using --verbose.

Available in v 0.0.9, just published.

Thanks
