### ISSUE TITLE
unchanged files seen as changed

### ISSUE THREAD

**Issue by fschell** [clavery/grunt-copy-to#4]
I have got a random number of changed files even if there was no change

after changing line 42 from 
  fs.utimesSync(dest, stats.mtime, stats.mtime);
to
  fs.utimesSync(dest, stats.atime, stats.mtime);

it works perfect

**Comment by clavery** [comment]
You're correct. Looks like a mistake on my part.

I pushed the fix and published v0.0.10

Thank You.

**Comment by fschell** [comment]
After I have still unchanged files which are seen as changed I detected it was caused by the 2 secs resolution of a file timestamp on windows (strange!). So if we want to copy only changed files on windows the if must be like:
if (mtime - destMtime > 2000){
...
